remote_theme: just-the-docs/just-the-docs
url: https://rareicon.com
author:
  name: KBVE

footer_content: true
footer_siderbar: true


title: "RareIcon.com"


plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions
  - jeql
  - premonition
  - jekyll-gzip
  - jekyll-redirect-from


jekyll-mentions:
  base_url: https://kbve.com/u

jeql:
  github:
    url: "https://api.github.com/graphql"